"""Pure tag registry constants and value objects."""
from dataclasses import dataclass


_UNSORTED_CATEGORY_SLUG = "unsorted"

MAX_ACTIVE_CATEGORIES = 10

TAG_STATUS_ACTIVE = "active"
TAG_STATUS_UNCATEGORIZED = "uncategorized"
TAG_STATUS_ARCHIVED = "archived"
TAG_STATUS_HIDDEN = "hidden"

TAG_LIFECYCLE_METADATA_RENAME = "rename"
TAG_LIFECYCLE_METADATA_MERGE = "merge"
TAG_LIFECYCLE_METADATA_ARCHIVE = "archive"
TAG_LIFECYCLE_METADATA_RESTORE = "restore"
TAG_LIFECYCLE_METADATA_ASSIGN_CATEGORY = "assign_category"
TAG_LIFECYCLE_METADATA_HIDE = "hide"
TAG_LIFECYCLE_METADATA_DELETE = "delete"
TAG_LIFECYCLE_METADATA_IMPORT_ARCHIVED = "import_archived"
TAG_LIFECYCLE_METADATA_IMPORT_UNCATEGORIZED = "import_uncategorized"

LIFECYCLE_STATE_ACTIVE = "active"
LIFECYCLE_STATE_ARCHIVED = "archived"
LIFECYCLE_STATE_HIDDEN = "hidden"
ARCHIVE_ORIGIN_IMPORTED = "imported"
ARCHIVE_ORIGIN_DELETED = "deleted"
ARCHIVE_REASON_UNKNOWN_IMPORT = "unknown_import"
ARCHIVE_REASON_USER_SOFT_DELETE = "user_soft_delete"
ARCHIVE_BADGE_IMPORTED = "Imported"
ARCHIVE_BADGE_DELETED = "Deleted"
ACTIVATION_ORIGIN_IMPORTED_ASSIGNMENT = "imported_assignment"
HIDE_REASON_HIDDEN_FROM_ARCHIVE = "hidden_from_archive"
RESOLVER_BEHAVIOR_MAP_TO_TARGET = "map_to_target"

TAG_CURRENT_METADATA_ACTIONS = [
    TAG_LIFECYCLE_METADATA_IMPORT_ARCHIVED,
    TAG_LIFECYCLE_METADATA_IMPORT_UNCATEGORIZED,
    TAG_LIFECYCLE_METADATA_ARCHIVE,
    TAG_LIFECYCLE_METADATA_RESTORE,
    TAG_LIFECYCLE_METADATA_ASSIGN_CATEGORY,
    TAG_LIFECYCLE_METADATA_HIDE,
    TAG_LIFECYCLE_METADATA_DELETE,
]
TAG_ALIAS_METADATA_ACTIONS = [
    TAG_LIFECYCLE_METADATA_RENAME,
    TAG_LIFECYCLE_METADATA_MERGE,
]

TAG_RESOLUTION_ACTIVE = "active"
TAG_RESOLUTION_ALIAS_MAPPED = "alias_mapped"
TAG_RESOLUTION_ARCHIVED = "archived"
TAG_RESOLUTION_HIDDEN = "hidden"
TAG_RESOLUTION_RETIRED = "retired"
TAG_RESOLUTION_UNKNOWN = "unknown"


@dataclass(frozen=True)
class TagResolutionResult:
    """Lifecycle resolution result for one imported tag value."""

    raw: str
    normalized_slug: str
    normalized_display_name: str
    resolved_slug: str
    result_type: str
    should_rewrite_slug: bool = False
    should_create_archived: bool = False
    should_skip_creation: bool = False
    target_slug: str | None = None
    reason: str = ""


__all__ = [
    "_UNSORTED_CATEGORY_SLUG",
    "ACTIVATION_ORIGIN_IMPORTED_ASSIGNMENT",
    "ARCHIVE_BADGE_DELETED",
    "ARCHIVE_BADGE_IMPORTED",
    "ARCHIVE_ORIGIN_DELETED",
    "ARCHIVE_ORIGIN_IMPORTED",
    "ARCHIVE_REASON_UNKNOWN_IMPORT",
    "ARCHIVE_REASON_USER_SOFT_DELETE",
    "HIDE_REASON_HIDDEN_FROM_ARCHIVE",
    "LIFECYCLE_STATE_ACTIVE",
    "LIFECYCLE_STATE_ARCHIVED",
    "LIFECYCLE_STATE_HIDDEN",
    "MAX_ACTIVE_CATEGORIES",
    "RESOLVER_BEHAVIOR_MAP_TO_TARGET",
    "TAG_ALIAS_METADATA_ACTIONS",
    "TAG_CURRENT_METADATA_ACTIONS",
    "TAG_LIFECYCLE_METADATA_ARCHIVE",
    "TAG_LIFECYCLE_METADATA_ASSIGN_CATEGORY",
    "TAG_LIFECYCLE_METADATA_DELETE",
    "TAG_LIFECYCLE_METADATA_HIDE",
    "TAG_LIFECYCLE_METADATA_IMPORT_ARCHIVED",
    "TAG_LIFECYCLE_METADATA_IMPORT_UNCATEGORIZED",
    "TAG_LIFECYCLE_METADATA_MERGE",
    "TAG_LIFECYCLE_METADATA_RENAME",
    "TAG_LIFECYCLE_METADATA_RESTORE",
    "TAG_RESOLUTION_ACTIVE",
    "TAG_RESOLUTION_ALIAS_MAPPED",
    "TAG_RESOLUTION_ARCHIVED",
    "TAG_RESOLUTION_HIDDEN",
    "TAG_RESOLUTION_RETIRED",
    "TAG_RESOLUTION_UNKNOWN",
    "TAG_STATUS_ACTIVE",
    "TAG_STATUS_ARCHIVED",
    "TAG_STATUS_HIDDEN",
    "TAG_STATUS_UNCATEGORIZED",
    "TagResolutionResult",
]
