"""Streamlit diagnostics page generated by LitLaunch.

This file is app-owned after generation. You can edit, theme, move, or replace
it to match your Streamlit application.
"""

from __future__ import annotations

from html import escape
from pathlib import Path
import json
import os
import traceback
from typing import Any


APP_NAME = 'RoleThread Lite'
PROFILE_NAME = 'rolethread-webapp'
PROJECT_ROOT = '.'
INCLUDE_EVENTS = True
EVENT_LOG_PATH = '.litlaunch\\runtime-events.log'
EVENT_LOG_ENV_VAR = 'ROLETHREAD_LAUNCHER_LOG_PATH'
PAGE_TITLE = 'Runtime Diagnostics'
THEME = 'auto'


_THEME_DARK = {
    "blue": "#1A73E8",
    "ok": "#3EB489",
    "warning": "#F4F15A",
    "error": "#E74C3C",
    "surface": "#202326",
    "surface_soft": "rgba(32, 35, 38, 0.72)",
    "text": "#E8E8E8",
    "surface_text": "#E8E8E8",
    "message": "#C9D1D9",
    "muted": "#8B949E",
    "border": "rgba(232, 232, 232, 0.12)",
    "row_border": "rgba(232, 232, 232, 0.10)",
    "info_bg": "rgba(26, 115, 232, 0.08)",
    "ok_bg": "rgba(62, 180, 137, 0.10)",
    "ok_pill_bg": "rgba(62, 180, 137, 0.14)",
    "warning_bg": "rgba(244, 241, 90, 0.13)",
    "error_bg": "rgba(231, 76, 60, 0.13)",
    "error_pill_bg": "rgba(231, 76, 60, 0.14)",
    "chart_bg": "#101418",
    "chart_text": "#E8E8E8",
    "chart_grid": "rgba(232, 232, 232, 0.16)",
    "code_bg": "#161B22",
    "code_text": "#E8E8E8",
}


_THEME_LIGHT = {
    "blue": "#1A73E8",
    "ok": "#178A5A",
    "warning": "#8A6D00",
    "error": "#C2413A",
    "page_bg": "#F6F8FA",
    "surface": "#F6F8FA",
    "surface_strong": "#FFFFFF",
    "surface_soft": "rgba(246, 248, 250, 0.92)",
    "text": "#24292F",
    "surface_text": "#24292F",
    "message": "#30363D",
    "muted": "#4B5563",
    "border": "rgba(31, 35, 40, 0.14)",
    "row_border": "rgba(31, 35, 40, 0.12)",
    "info_bg": "rgba(26, 115, 232, 0.08)",
    "ok_bg": "rgba(23, 138, 90, 0.10)",
    "ok_pill_bg": "rgba(23, 138, 90, 0.14)",
    "warning_bg": "rgba(251, 191, 36, 0.18)",
    "error_bg": "rgba(194, 65, 58, 0.12)",
    "error_pill_bg": "rgba(194, 65, 58, 0.14)",
    "chart_bg": "#FFFFFF",
    "chart_text": "#24292F",
    "chart_grid": "rgba(31, 35, 40, 0.14)",
    "code_bg": "#182234",
    "code_text": "#E8F0FE",
}


_THEME_AUTO = {
    "blue": "var(--primary-color, #1A73E8)",
    "ok": "#3EB489",
    "warning": "#F4F15A",
    "error": "#E74C3C",
    "surface": "var(--secondary-background-color, #202326)",
    "surface_soft": "var(--secondary-background-color, rgba(32, 35, 38, 0.72))",
    "text": "var(--text-color, #E8E8E8)",
    "surface_text": "var(--text-color, #E8E8E8)",
    "message": "var(--text-color, #C9D1D9)",
    "muted": "#8B949E",
    "border": "rgba(128, 128, 128, 0.22)",
    "row_border": "rgba(128, 128, 128, 0.18)",
    "info_bg": "rgba(26, 115, 232, 0.08)",
    "ok_bg": "rgba(62, 180, 137, 0.10)",
    "ok_pill_bg": "rgba(62, 180, 137, 0.14)",
    "warning_bg": "rgba(244, 241, 90, 0.13)",
    "error_bg": "rgba(231, 76, 60, 0.13)",
    "error_pill_bg": "rgba(231, 76, 60, 0.14)",
    "chart_bg": "#101418",
    "chart_text": "#E8E8E8",
    "chart_grid": "rgba(232, 232, 232, 0.16)",
    "code_bg": "#161B22",
    "code_text": "#E8E8E8",
}


def render_litlaunch_diagnostics() -> None:
    """Render the generated LitLaunch diagnostics support page."""

    import streamlit as st

    _inject_litlaunch_styles(st)
    st.title(PAGE_TITLE)
    _render_page_intro(st)

    report, error_message, error_detail = _collect_diagnostics()
    if report is None:
        _render_collection_error(st, error_message, error_detail)
        return

    data = report.to_dict()
    _render_summary(st, data)
    _render_posture_cards(st, data)
    _render_operational_snapshot(st, data)
    _render_artifact_actions(st, report)
    _render_sections(st, data)
    _render_event_trail(st)


def _collect_diagnostics() -> tuple[Any | None, str | None, str | None]:
    try:
        from litlaunch import DiagnosticCollector, load_profile

        profile = None
        profile_config = None
        if PROFILE_NAME:
            profile = load_profile(PROFILE_NAME, cwd=_project_root())
            profile_config = profile.config

        collector = DiagnosticCollector()
        report = collector.collect(
            app_path=profile_config.app_path if profile_config else None,
            mode=profile_config.mode if profile_config else "browser",
            browser=profile_config.browser if profile_config else "auto",
            host=profile_config.host if profile_config else "127.0.0.1",
            port=profile_config.port if profile_config else None,
            auto_port=profile_config.auto_port if profile_config else True,
            allow_browser_fallback=(
                profile_config.allow_browser_fallback if profile_config else True
            ),
            allow_network_exposure=(
                profile_config.allow_network_exposure if profile_config else False
            ),
            trust_mode=profile_config.trust_mode if profile_config else "development",
            cwd=profile_config.cwd if profile_config else _project_root(),
            extra_env=profile_config.extra_env if profile_config else None,
            streamlit_flags=profile_config.streamlit_flags if profile_config else {},
            streamlit_args=profile_config.streamlit_args if profile_config else (),
            app_args=profile_config.app_args if profile_config else (),
            profile_name=profile.name if profile else None,
            monitor_window=profile.monitor_window if profile else None,
            graceful_timeout_seconds=(
                profile.graceful_timeout_seconds if profile else None
            ),
            window_monitor_config=profile.window_monitor_config if profile else None,
        )
        return report, None, None
    except Exception as exc:
        return None, f"{type(exc).__name__}: {exc}", traceback.format_exc()


def _inject_litlaunch_styles(st: Any) -> None:
    theme = _theme_tokens()
    light_page_override = ""
    if THEME == "light":
        light_page_override = f"""
.stApp {{
    background: {theme["page_bg"]};
    color: {theme["text"]};
}}
[data-testid="stAppViewContainer"],
[data-testid="stHeader"] {{
    background: {theme["page_bg"]};
}}
[data-testid="stExpander"] details {{
    background: {theme["surface_strong"]};
    border-color: {theme["border"]};
}}
[data-testid="stExpander"] summary {{
    color: {theme["text"]};
}}
[data-testid="stExpander"] details[open] summary {{
    background: {theme["surface_strong"]};
    border-bottom: 1px solid {theme["border"]};
}}
[data-testid="stSelectbox"] div[data-baseweb="select"] > div {{
    background: {theme["surface_strong"]};
    border-color: {theme["border"]};
    color: {theme["text"]};
}}
[data-testid="stSelectbox"] svg {{
    color: {theme["ok"]};
}}
[data-testid="stDownloadButton"] button,
[data-testid="stButton"] button {{
    background: {theme["surface_strong"]};
    border-color: {theme["border"]};
    color: {theme["text"]};
}}
[data-testid="stVegaLiteChart"] {{
    background: {theme["surface_strong"]};
    border: 1px solid {theme["border"]};
    border-radius: 0.35rem;
    padding: 0.25rem;
}}
[data-testid="stCodeBlock"] pre {{
    background: {theme["code_bg"]};
    border: 1px solid {theme["row_border"]};
    border-radius: 0.42rem;
    color: {theme["code_text"]};
}}
[data-testid="stCodeBlock"] code {{
    color: {theme["code_text"]};
}}
"""
    st.markdown(
        f"""
<style>
{light_page_override}
.litlaunch-meta-row {{
    align-items: center;
    display: flex;
    flex-wrap: wrap;
    gap: 0.55rem;
    margin: 0.35rem 0 0.2rem 0;
}}
.litlaunch-meta-label {{
    color: {theme["blue"]};
    font-size: 0.88rem;
    font-weight: 700;
}}
.litlaunch-slug {{
    background: {theme["surface"]};
    border: 1px solid rgba(62, 180, 137, 0.35);
    border-radius: 0.35rem;
    color: {theme["ok"]};
    display: inline-block;
    font-family: ui-monospace, SFMono-Regular, Consolas, "Liberation Mono", monospace;
    font-size: 0.84rem;
    font-weight: 700;
    line-height: 1.35;
    padding: 0.14rem 0.42rem;
}}
.litlaunch-muted {{
    color: {theme["muted"]};
    font-size: 0.9rem;
    line-height: 1.45;
}}
.litlaunch-section {{
    margin-top: 2.05rem;
}}
.litlaunch-section-compact {{
    margin-top: 1.35rem;
}}
.litlaunch-summary-value {{
    font-size: 2rem;
    font-weight: 700;
    line-height: 1.15;
    margin-top: 0.12rem;
}}
.litlaunch-summary-label {{
    color: {theme["text"]};
    font-size: 0.88rem;
    line-height: 1.35;
}}
.litlaunch-text-ok {{
    color: {theme["ok"]};
}}
.litlaunch-text-info {{
    color: {theme["warning"]};
}}
.litlaunch-text-warning {{
    color: {theme["warning"]};
}}
.litlaunch-text-error {{
    color: {theme["error"]};
}}
.litlaunch-notice {{
    border-left: 3px solid #1A73E8;
    border-radius: 0.42rem;
    margin: 0.45rem 0;
    padding: 0.55rem 0.75rem;
    color: {theme["text"]};
}}
.litlaunch-notice-info {{
    background: {theme["info_bg"]};
    border-left-color: {theme["blue"]};
}}
.litlaunch-notice-ok {{
    background: {theme["ok_bg"]};
    border-left-color: {theme["ok"]};
}}
.litlaunch-notice-warning {{
    background: {theme["warning_bg"]};
    border-left-color: {theme["warning"]};
}}
.litlaunch-notice-error {{
    background: {theme["error_bg"]};
    border-left-color: {theme["error"]};
}}
.litlaunch-posture-card {{
    background: {theme["surface"]};
    border: 1px solid {theme["border"]};
    border-left: 4px solid {theme["blue"]};
    border-radius: 0.48rem;
    min-height: 6rem;
    padding: 0.72rem 0.78rem;
}}
.litlaunch-posture-label {{
    color: {theme["blue"]};
    font-size: 0.82rem;
    font-weight: 800;
    margin-bottom: 0.35rem;
}}
.litlaunch-posture-value {{
    color: {theme["surface_text"]};
    font-size: 1.18rem;
    font-weight: 750;
    line-height: 1.25;
}}
.litlaunch-posture-status {{
    color: {theme["muted"]};
    font-size: 0.78rem;
    margin-top: 0.38rem;
}}
.litlaunch-status-ok {{
    border-left-color: {theme["ok"]};
}}
.litlaunch-status-info {{
    border-left-color: {theme["warning"]};
}}
.litlaunch-status-warning {{
    border-left-color: {theme["warning"]};
}}
.litlaunch-status-error {{
    border-left-color: {theme["error"]};
}}
.litlaunch-row {{
    background: {theme["surface_soft"]};
    border: 1px solid {theme["row_border"]};
    border-left: 3px solid {theme["blue"]};
    border-radius: 0.42rem;
    margin: 0.42rem 0;
    padding: 0.55rem 0.7rem;
}}
.litlaunch-row-title {{
    color: {theme["surface_text"]};
    font-weight: 750;
}}
.litlaunch-row-message {{
    color: {theme["message"]};
    margin-top: 0.12rem;
}}
.litlaunch-row-detail {{
    color: {theme["muted"]};
    font-size: 0.86rem;
    margin-top: 0.28rem;
}}
.litlaunch-pill {{
    border-radius: 999px;
    display: inline-block;
    font-size: 0.72rem;
    font-weight: 800;
    margin-right: 0.45rem;
    padding: 0.05rem 0.42rem;
    text-transform: uppercase;
}}
.litlaunch-pill-ok {{
    background: {theme["ok_pill_bg"]};
    color: {theme["ok"]};
}}
.litlaunch-pill-info {{
    background: {theme["warning_bg"]};
    color: {theme["warning"]};
}}
.litlaunch-pill-warning {{
    background: {theme["warning_bg"]};
    color: {theme["warning"]};
}}
.litlaunch-pill-error {{
    background: {theme["error_pill_bg"]};
    color: {theme["error"]};
}}
</style>
        """,
        unsafe_allow_html=True,
    )


def _theme_tokens() -> dict[str, str]:
    if THEME == "dark":
        return _THEME_DARK
    if THEME == "light":
        return _THEME_LIGHT
    return _THEME_AUTO


def _chart_theme_tokens() -> dict[str, str]:
    if THEME == "light":
        return _THEME_LIGHT
    return _THEME_DARK


def _chart_config(theme: dict[str, str]) -> dict[str, Any]:
    return {
        "background": theme["chart_bg"],
        "axis": {
            "domainColor": theme["chart_grid"],
            "gridColor": theme["chart_grid"],
            "labelColor": theme["chart_text"],
            "titleColor": theme["chart_text"],
        },
        "legend": {
            "labelColor": theme["chart_text"],
            "titleColor": theme["chart_text"],
        },
        "view": {"stroke": "transparent"},
    }


def _chart_axis_config(theme: dict[str, str], *, title: str) -> dict[str, str]:
    return {
        "domainColor": theme["chart_grid"],
        "gridColor": theme["chart_grid"],
        "labelColor": theme["chart_text"],
        "title": title,
        "titleColor": theme["chart_text"],
    }


def _render_page_intro(st: Any) -> None:
    st.caption(
        "A Streamlit-native support surface generated by LitLaunch and owned by "
        "this application."
    )
    if APP_NAME or PROFILE_NAME:
        parts: list[str] = []
        if APP_NAME:
            parts.append(_meta_pair("App", APP_NAME))
        if PROFILE_NAME:
            parts.append(_meta_pair("LitLaunch profile", PROFILE_NAME))
        st.markdown(
            f"<div class='litlaunch-meta-row'>{''.join(parts)}</div>",
            unsafe_allow_html=True,
        )


def _render_collection_error(st: Any, message: str | None, detail: str | None) -> None:
    st.error("Could not collect LitLaunch diagnostics.")
    if message:
        st.caption(message)
    if detail:
        with st.expander("Technical details"):
            st.code(detail)


def _render_summary(st: Any, data: dict[str, Any]) -> None:
    _render_section_spacer(st)
    st.subheader("Runtime Summary")
    columns = st.columns(4)
    errors = int(data.get("errors", 0) or 0)
    warnings = int(data.get("warnings", 0) or 0)
    diagnostics_status = "OK" if data.get("ok") else "Needs attention"
    diagnostics_level = "ok" if data.get("ok") else ("error" if errors else "warning")
    with columns[0]:
        _render_summary_value(st, "Diagnostics", diagnostics_status, diagnostics_level)
    with columns[1]:
        _render_summary_value(st, "Errors", str(errors), "error" if errors else "ok")
    with columns[2]:
        _render_summary_value(
            st,
            "Warnings",
            str(warnings),
            "warning" if warnings else "ok",
        )
    with columns[3]:
        _render_summary_value(
            st,
            "LitLaunch",
            str(data.get("litlaunch_version", "unknown")),
            "ok",
        )

    metadata = {
        "App": APP_NAME or "not configured",
        "Profile": PROFILE_NAME or "not configured",
        "Project root": str(_project_root()),
        "Generated": str(data.get("generated_at_utc", "unknown")),
    }
    _render_section_spacer(st, compact=True)
    with st.expander("Runtime metadata", expanded=False):
        _render_key_value_rows(st, metadata)


def _render_posture_cards(st: Any, data: dict[str, Any]) -> None:
    _render_section_spacer(st)
    st.subheader("Posture")
    sections = _sections(data)
    cards = (
        (
            "Runtime Governance",
            _item_message(sections, "Runtime Governance", "Launch posture"),
            _item_status(sections, "Runtime Governance", "Launch posture"),
        ),
        (
            "Runtime Exposure",
            _item_message(sections, "Runtime Exposure", "Exposure scope"),
            _item_status(sections, "Runtime Exposure", "Exposure scope"),
        ),
        (
            "Transport Security",
            _item_message(sections, "Transport Security", "TLS configuration"),
            _item_status(sections, "Transport Security", "TLS configuration"),
        ),
        (
            "Browser/Platform",
            _item_message(sections, "Browsers", "Browser resolution"),
            _item_status(sections, "Browsers", "Browser resolution"),
        ),
    )
    columns = st.columns(len(cards))
    for column, (label, value, status) in zip(columns, cards):
        with column:
            _render_posture_card(st, label, _compact_metric_value(label, value), status)


def _render_operational_snapshot(st: Any, data: dict[str, Any]) -> None:
    _render_section_spacer(st)
    st.subheader("Operational Snapshot")
    status_column, activity_column = st.columns(2)
    with status_column:
        _render_status_mix_chart(st, data)
    with activity_column:
        event_counts = _event_category_counts()
        if event_counts:
            _render_event_mix_chart(st, event_counts)
        else:
            _render_section_attention_chart(st, data)


def _render_status_mix_chart(st: Any, data: dict[str, Any]) -> None:
    st.markdown("**Diagnostics Status Mix**")
    rows = _status_mix_rows(data)
    theme = _chart_theme_tokens()
    spec = {
        "background": theme["chart_bg"],
        "height": 220,
        "mark": {"type": "bar", "cornerRadiusEnd": 3},
        "encoding": {
            "y": {
                "field": "status",
                "type": "nominal",
                "sort": None,
                "axis": _chart_axis_config(theme, title="status"),
            },
            "x": {
                "field": "count",
                "type": "quantitative",
                "axis": _chart_axis_config(theme, title="count"),
            },
            "color": {
                "field": "color",
                "type": "nominal",
                "scale": None,
                "legend": None,
            },
            "tooltip": [
                {"field": "status", "type": "nominal"},
                {"field": "count", "type": "quantitative"},
            ],
        },
        "config": _chart_config(theme),
    }
    st.vega_lite_chart(
        rows,
        spec,
        width="stretch",
    )


def _render_event_mix_chart(st: Any, counts: dict[str, int]) -> None:
    st.markdown("**Runtime Event Mix**")
    rows = [
        {"category": category, "count": count}
        for category, count in sorted(counts.items())
    ]
    theme = _chart_theme_tokens()
    spec = {
        "background": theme["chart_bg"],
        "height": 220,
        "mark": {"type": "bar", "cornerRadiusEnd": 3},
        "encoding": {
            "x": {
                "field": "category",
                "type": "nominal",
                "axis": _chart_axis_config(theme, title="category"),
            },
            "y": {
                "field": "count",
                "type": "quantitative",
                "axis": _chart_axis_config(theme, title="count"),
            },
            "color": {"value": theme["ok"]},
            "tooltip": [
                {"field": "category", "type": "nominal"},
                {"field": "count", "type": "quantitative"},
            ],
        },
        "config": _chart_config(theme),
    }
    st.vega_lite_chart(
        rows,
        spec,
        width="stretch",
    )


def _render_section_attention_chart(st: Any, data: dict[str, Any]) -> None:
    st.markdown("**Section Attention Map**")
    rows = _section_attention_rows(data)
    if not rows:
        _render_notice(st, "info", "No section attention data is available.")
        return
    theme = _chart_theme_tokens()
    spec = {
        "background": theme["chart_bg"],
        "height": 220,
        "mark": {"type": "bar", "cornerRadiusEnd": 3},
        "transform": [{"fold": ["errors", "warnings"], "as": ["severity", "count"]}],
        "encoding": {
            "x": {
                "field": "section",
                "type": "nominal",
                "axis": _chart_axis_config(theme, title="section"),
            },
            "y": {
                "field": "count",
                "type": "quantitative",
                "axis": _chart_axis_config(theme, title="count"),
            },
            "color": {
                "field": "severity",
                "type": "nominal",
                "scale": {
                    "domain": ["errors", "warnings"],
                    "range": [theme["error"], theme["warning"]],
                },
            },
            "tooltip": [
                {"field": "section", "type": "nominal"},
                {"field": "severity", "type": "nominal"},
                {"field": "count", "type": "quantitative"},
            ],
        },
        "config": _chart_config(theme),
    }
    st.vega_lite_chart(
        rows,
        spec,
        width="stretch",
    )


def _render_artifact_actions(st: Any, report: Any) -> None:
    from litlaunch import (
        HTMLDiagnosticsRenderer,
        JSONDiagnosticsRenderer,
        SanitizedBundleRenderer,
    )

    html_report = HTMLDiagnosticsRenderer(include_details=True).render(report)
    json_report = JSONDiagnosticsRenderer().render(report)
    support_bundle = SanitizedBundleRenderer(include_details=True).render(report)
    artifacts = {
        "HTML report": {
            "file_name": "litlaunch-report.html",
            "content": html_report,
            "mime": "text/html",
        },
        "JSON diagnostics": {
            "file_name": "litlaunch-report.json",
            "content": json_report,
            "mime": "application/json",
        },
        "Support bundle": {
            "file_name": "litlaunch-support-bundle.txt",
            "content": support_bundle,
            "mime": "text/plain",
        },
    }

    _render_section_spacer(st)
    st.subheader("Support Artifacts")
    _render_muted(
        st,
        "Downloads are generated in memory. Writes create persistent artifacts "
        "under .litlaunch/reports/.",
    )
    download_column, write_column = st.columns(2)
    _render_download_artifact_group(st, download_column, artifacts)
    _render_write_artifact_group(st, write_column, artifacts)


def _render_download_artifact_group(
    st: Any,
    column: Any,
    artifacts: dict[str, dict[str, str]],
) -> None:
    with column:
        label = st.selectbox(
            "Download Artifact",
            options=list(artifacts),
            key="litlaunch_download_artifact_select",
        )
        artifact = artifacts[label]
        st.download_button(
            "Download",
            data=artifact["content"].encode("utf-8"),
            file_name=artifact["file_name"],
            mime=artifact["mime"],
            key="litlaunch_download_artifact_button",
        )


def _render_write_artifact_group(
    st: Any,
    column: Any,
    artifacts: dict[str, dict[str, str]],
) -> None:
    with column:
        label = st.selectbox(
            "Write Artifact",
            options=list(artifacts),
            key="litlaunch_write_artifact_select",
        )
        artifact = artifacts[label]
        if st.button("Write", key="litlaunch_write_artifact_button"):
            path = _write_report_artifact(artifact["file_name"], artifact["content"])
            _render_notice(st, "ok", f"Wrote {label}.")
            st.code(str(path))


def _write_report_artifact(file_name: str, content: str) -> Path:
    from litlaunch.artifacts import reports_dir

    report_dir = reports_dir(_project_root(), create=True)
    output_path = report_dir / file_name
    output_path.write_text(content, encoding="utf-8")
    return output_path


def _render_sections(st: Any, data: dict[str, Any]) -> None:
    _render_section_spacer(st)
    st.subheader("Diagnostics Details")
    sections = _sections(data)
    for section in data.get("sections", []):
        title = str(section.get("title", "Untitled section"))
        status = _section_status(sections, title)
        expanded = title in {
            "Runtime Governance",
            "Runtime Exposure",
            "Transport Security",
        }
        with st.expander(f"{title} - {status}", expanded=expanded):
            for item in section.get("items", []):
                _render_item(st, item)


def _render_item(st: Any, item: dict[str, Any]) -> None:
    status = str(item.get("status", "info")).lower()
    name = str(item.get("name", "Item"))
    message = str(item.get("message", ""))
    detail = item.get("detail")
    _render_diagnostic_row(st, status, name, message, str(detail) if detail else None)


def _render_event_trail(st: Any) -> None:
    if not INCLUDE_EVENTS:
        return

    _render_section_spacer(st)
    st.subheader("Runtime Event Trail")
    event_path = _runtime_event_log_path()
    if event_path is None:
        _render_notice(
            st,
            "info",
            "No runtime event log path is configured for this generated page.",
        )
        return

    if not event_path.is_file():
        _render_notice(st, "info", "No runtime event log found.")
        st.code(str(event_path))
        return

    lines = event_path.read_text(encoding="utf-8", errors="replace").splitlines()
    recent_lines = lines[-80:]
    _render_muted(st, f"Showing {len(recent_lines)} recent lines from:")
    st.code(str(event_path))
    st.code("\n".join(recent_lines) or "No events recorded yet.")


def _status_mix_rows(data: dict[str, Any]) -> list[dict[str, Any]]:
    theme = _chart_theme_tokens()
    counts = {"ok": 0, "info": 0, "warning": 0, "error": 0}
    for section in data.get("sections", []):
        for item in section.get("items", []):
            status = _normalize_status(str(item.get("status", "info")))
            counts[status] += 1
    return [
        {"status": "OK", "count": counts["ok"], "color": theme["ok"]},
        {"status": "Info", "count": counts["info"], "color": theme["blue"]},
        {"status": "Warning", "count": counts["warning"], "color": theme["warning"]},
        {"status": "Error", "count": counts["error"], "color": theme["error"]},
    ]


def _section_attention_rows(data: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for section in data.get("sections", []):
        title = str(section.get("title", "Untitled"))
        warning_count = 0
        error_count = 0
        for item in section.get("items", []):
            status = _normalize_status(str(item.get("status", "info")))
            if status == "warning":
                warning_count += 1
            elif status == "error":
                error_count += 1
        if warning_count or error_count:
            rows.append(
                {
                    "section": title,
                    "warnings": warning_count,
                    "errors": error_count,
                }
            )
    return rows


def _event_category_counts() -> dict[str, int]:
    if not INCLUDE_EVENTS:
        return {}
    event_path = _runtime_event_log_path()
    if event_path is None:
        return {}
    if not event_path.is_file():
        return {}
    counts: dict[str, int] = {}
    for line in event_path.read_text(encoding="utf-8", errors="replace").splitlines():
        category = _extract_event_category(line)
        if category:
            counts[category] = counts.get(category, 0) + 1
    return counts


def _extract_event_category(line: str) -> str | None:
    json_category = _extract_json_event_category(line)
    if json_category:
        return json_category

    marker = "category="
    if marker in line:
        category = line.split(marker, 1)[1].split()[0].strip(" ,;")
        return category or None
    if "litlaunch_event" in line:
        parts = line.split()
        if len(parts) >= 4:
            value = parts[3].strip("[]")
            return value or None
    return None


def _extract_json_event_category(line: str) -> str | None:
    text = line.strip()
    if not text.startswith("{"):
        return None
    try:
        record = json.loads(text)
    except Exception:
        return None
    if not isinstance(record, dict):
        return None
    category = record.get("category")
    if not isinstance(category, str):
        return None
    category = category.strip()
    return category or None


def _render_posture_card(st: Any, label: str, value: str, status: str) -> None:
    status_class = _status_class(status)
    status_label = _status_label(status)
    st.markdown(
        (
            f"<div class='litlaunch-posture-card {status_class}'>"
            f"<div class='litlaunch-posture-label'>{_html(label)}</div>"
            f"<div class='litlaunch-posture-value'>{_html(value)}</div>"
            f"<div class='litlaunch-posture-status'>{_html(status_label)}</div>"
            "</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_summary_value(st: Any, label: str, value: str, status: str) -> None:
    status_class = f"litlaunch-text-{_normalize_status(status)}"
    st.markdown(
        (
            "<div>"
            f"<div class='litlaunch-summary-label'>{_html(label)}</div>"
            f"<div class='litlaunch-summary-value {status_class}'>{_html(value)}</div>"
            "</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_diagnostic_row(
    st: Any,
    status: str,
    name: str,
    message: str,
    detail: str | None,
) -> None:
    normalized = _normalize_status(status)
    detail_html = (
        f"<div class='litlaunch-row-detail'>{_html(detail)}</div>" if detail else ""
    )
    st.markdown(
        (
            f"<div class='litlaunch-row {_status_class(normalized)}'>"
            f"<span class='litlaunch-pill litlaunch-pill-{normalized}'>"
            f"{_html(_status_label(normalized))}</span>"
            f"<span class='litlaunch-row-title'>{_html(name)}</span>"
            f"<div class='litlaunch-row-message'>{_html(message)}</div>"
            f"{detail_html}</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_key_value_rows(st: Any, rows: dict[str, Any]) -> None:
    for label, value in rows.items():
        st.markdown(
            (
                "<div class='litlaunch-meta-row'>"
                f"<span class='litlaunch-meta-label'>{_html(str(label))}</span>"
                f"<span class='litlaunch-slug'>{_html(str(value))}</span>"
                "</div>"
            ),
            unsafe_allow_html=True,
        )


def _render_notice(st: Any, status: str, message: str) -> None:
    normalized = _normalize_status(status)
    st.markdown(
        (
            f"<div class='litlaunch-notice litlaunch-notice-{normalized}'>"
            f"{_html(message)}</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_muted(st: Any, message: str) -> None:
    st.markdown(
        f"<div class='litlaunch-muted'>{_html(message)}</div>",
        unsafe_allow_html=True,
    )


def _render_section_spacer(st: Any, *, compact: bool = False) -> None:
    class_name = "litlaunch-section-compact" if compact else "litlaunch-section"
    st.markdown(f"<div class='{class_name}'></div>", unsafe_allow_html=True)


def _meta_pair(label: str, value: str) -> str:
    return (
        f"<span class='litlaunch-meta-label'>{_html(label)}</span>"
        f"<span class='litlaunch-slug'>{_html(value)}</span>"
    )


def _html(value: Any) -> str:
    return escape(str(value), quote=True)


def _normalize_status(status: str) -> str:
    normalized = str(status or "info").lower()
    if normalized in {"ok", "info", "warning", "error"}:
        return normalized
    return "info"


def _status_class(status: str) -> str:
    return f"litlaunch-status-{_normalize_status(status)}"


def _status_label(status: str) -> str:
    normalized = _normalize_status(status)
    if normalized == "ok":
        return "OK"
    if normalized == "warning":
        return "Warning"
    if normalized == "error":
        return "Error"
    return "Info"


def _sections(data: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    return {
        str(section.get("title", "")): list(section.get("items", []))
        for section in data.get("sections", [])
    }


def _section_status(sections: dict[str, list[dict[str, Any]]], title: str) -> str:
    items = sections.get(title, [])
    statuses = {str(item.get("status", "info")).lower() for item in items}
    if "error" in statuses:
        return "error"
    if "warning" in statuses:
        return "warning"
    if "ok" in statuses:
        return "ok"
    return "info"


def _item_message(
    sections: dict[str, list[dict[str, Any]]],
    title: str,
    item_name: str,
) -> str | None:
    for item in sections.get(title, []):
        if item.get("name") == item_name:
            return str(item.get("message", ""))
    return None


def _item_status(
    sections: dict[str, list[dict[str, Any]]],
    title: str,
    item_name: str,
) -> str:
    for item in sections.get(title, []):
        if item.get("name") == item_name:
            return str(item.get("status", "info")).lower()
    return _section_status(sections, title)


def _compact_metric_value(label: str, value: str | None) -> str:
    if not value:
        return "not reported"
    normalized = value.strip()
    if label == "Transport Security":
        if normalized == "not_configured":
            return "No TLS"
        if normalized == "configured":
            return "TLS"
        if normalized == "incomplete":
            return "Incomplete"
    if label == "Browser/Platform":
        if "Microsoft Edge" in normalized:
            return "Edge"
        if "Chrome" in normalized or "Chromium" in normalized:
            return "Chrome"
        if "Default browser" in normalized:
            return "Default"
    if normalized == "wildcard_bind":
        return "wildcard"
    return normalized.replace("_", " ")


def _project_root() -> Path:
    if PROJECT_ROOT:
        return Path(PROJECT_ROOT).expanduser().resolve()
    return Path.cwd()


def _resolve_project_path(value: str) -> Path:
    path = Path(value).expanduser()
    if path.is_absolute():
        return path
    return _project_root() / path


def _runtime_event_log_path() -> Path | None:
    if EVENT_LOG_ENV_VAR:
        env_value = os.environ.get(EVENT_LOG_ENV_VAR)
        if env_value:
            return _resolve_project_path(env_value)
    if EVENT_LOG_PATH:
        return _resolve_project_path(EVENT_LOG_PATH)
    return None
