"""Streamlit diagnostics page generated by LitLaunch.

This file is app-owned after generation. You can edit, theme, move, or replace
it to match your Streamlit application.
"""

from __future__ import annotations

from datetime import datetime
from html import escape
from pathlib import Path
import json
import os
import traceback
from typing import Any


APP_NAME = 'RoleThread Lite'
PROFILE_NAME = 'rolethread-webapp'
PROJECT_ROOT = '.'
INCLUDE_EVENTS = True
EVENT_LOG_PATH = '.litlaunch\\runtime-events.log'
EVENT_LOG_ENV_VAR = 'ROLETHREAD_LAUNCHER_LOG_PATH'
PAGE_TITLE = 'Runtime Diagnostics'
THEME = 'auto'


_THEME_DARK = {
    "blue": "#1A73E8",
    "ok": "#3EB489",
    "warning": "#F4F15A",
    "error": "#E74C3C",
    "surface": "#202326",
    "surface_soft": "rgba(32, 35, 38, 0.72)",
    "text": "#E8E8E8",
    "surface_text": "#E8E8E8",
    "message": "#C9D1D9",
    "muted": "#8B949E",
    "border": "rgba(232, 232, 232, 0.12)",
    "row_border": "rgba(232, 232, 232, 0.10)",
    "info_bg": "rgba(26, 115, 232, 0.08)",
    "ok_bg": "rgba(62, 180, 137, 0.10)",
    "ok_pill_bg": "rgba(62, 180, 137, 0.14)",
    "warning_bg": "rgba(244, 241, 90, 0.13)",
    "error_bg": "rgba(231, 76, 60, 0.13)",
    "error_pill_bg": "rgba(231, 76, 60, 0.14)",
    "chart_bg": "#101418",
    "chart_text": "#E8E8E8",
    "chart_grid": "rgba(232, 232, 232, 0.16)",
    "code_bg": "#161B22",
    "code_text": "#E8E8E8",
}


_THEME_LIGHT = {
    "blue": "#1A73E8",
    "ok": "#178A5A",
    "warning": "#8A6D00",
    "error": "#C2413A",
    "page_bg": "#F6F8FA",
    "surface": "#F6F8FA",
    "surface_strong": "#FFFFFF",
    "surface_soft": "rgba(246, 248, 250, 0.92)",
    "text": "#24292F",
    "surface_text": "#24292F",
    "message": "#30363D",
    "muted": "#4B5563",
    "border": "rgba(31, 35, 40, 0.14)",
    "row_border": "rgba(31, 35, 40, 0.12)",
    "info_bg": "rgba(26, 115, 232, 0.08)",
    "ok_bg": "rgba(23, 138, 90, 0.10)",
    "ok_pill_bg": "rgba(23, 138, 90, 0.14)",
    "warning_bg": "rgba(251, 191, 36, 0.18)",
    "error_bg": "rgba(194, 65, 58, 0.12)",
    "error_pill_bg": "rgba(194, 65, 58, 0.14)",
    "chart_bg": "#FFFFFF",
    "chart_text": "#24292F",
    "chart_grid": "rgba(31, 35, 40, 0.14)",
    "code_bg": "#182234",
    "code_text": "#E8F0FE",
}


_THEME_AUTO = {
    "blue": "var(--primary-color, #1A73E8)",
    "ok": "#3EB489",
    "warning": "#F4F15A",
    "error": "#E74C3C",
    "surface": "var(--secondary-background-color, #202326)",
    "surface_soft": "var(--secondary-background-color, rgba(32, 35, 38, 0.72))",
    "text": "var(--text-color, #E8E8E8)",
    "surface_text": "var(--text-color, #E8E8E8)",
    "message": "var(--text-color, #C9D1D9)",
    "muted": "#8B949E",
    "border": "rgba(128, 128, 128, 0.22)",
    "row_border": "rgba(128, 128, 128, 0.18)",
    "info_bg": "rgba(26, 115, 232, 0.08)",
    "ok_bg": "rgba(62, 180, 137, 0.10)",
    "ok_pill_bg": "rgba(62, 180, 137, 0.14)",
    "warning_bg": "rgba(244, 241, 90, 0.13)",
    "error_bg": "rgba(231, 76, 60, 0.13)",
    "error_pill_bg": "rgba(231, 76, 60, 0.14)",
    "chart_bg": "#101418",
    "chart_text": "#E8E8E8",
    "chart_grid": "rgba(232, 232, 232, 0.16)",
    "code_bg": "#161B22",
    "code_text": "#E8E8E8",
}


def render_litlaunch_diagnostics() -> None:
    """Render the generated LitLaunch diagnostics support page."""

    import streamlit as st

    _inject_litlaunch_styles(st)
    st.title(PAGE_TITLE)
    _render_page_intro(st)

    report, error_message, error_detail = _collect_diagnostics()
    if report is None:
        _render_collection_error(st, error_message, error_detail)
        return

    data = report.to_dict()
    _render_summary(st, data)
    _render_posture_cards(st, data)
    _render_operational_snapshot(st, data)
    # RoleThread-owned product context layered on top of LitLaunch runtime diagnostics.
    from ui.diagnostics_product import render_product_diagnostics

    render_product_diagnostics()
    _render_artifact_actions(st, report)
    _render_sections(st, data)
    _render_runtime_sessions(st)


def _collect_diagnostics() -> tuple[Any | None, str | None, str | None]:
    try:
        from litlaunch import DiagnosticCollector, load_profile

        profile = None
        profile_config = None
        if PROFILE_NAME:
            profile = load_profile(PROFILE_NAME, cwd=_project_root())
            profile_config = profile.config

        collector = DiagnosticCollector()
        report = collector.collect(
            app_path=profile_config.app_path if profile_config else None,
            mode=profile_config.mode if profile_config else "browser",
            browser=profile_config.browser if profile_config else "auto",
            host=profile_config.host if profile_config else "127.0.0.1",
            port=profile_config.port if profile_config else None,
            auto_port=profile_config.auto_port if profile_config else True,
            allow_browser_fallback=(
                profile_config.allow_browser_fallback if profile_config else True
            ),
            allow_network_exposure=(
                profile_config.allow_network_exposure if profile_config else False
            ),
            trust_mode=profile_config.trust_mode if profile_config else "development",
            cwd=profile_config.cwd if profile_config else _project_root(),
            extra_env=profile_config.extra_env if profile_config else None,
            streamlit_flags=profile_config.streamlit_flags if profile_config else {},
            streamlit_args=profile_config.streamlit_args if profile_config else (),
            app_args=profile_config.app_args if profile_config else (),
            profile_name=profile.name if profile else None,
            monitor_window=profile.monitor_window if profile else None,
            graceful_timeout_seconds=(
                profile.graceful_timeout_seconds if profile else None
            ),
            window_monitor_config=profile.window_monitor_config if profile else None,
        )
        return report, None, None
    except Exception as exc:
        return None, f"{type(exc).__name__}: {exc}", traceback.format_exc()


def _inject_litlaunch_styles(st: Any) -> None:
    theme = _theme_tokens()
    light_page_override = ""
    if THEME == "light":
        light_page_override = f"""
.stApp {{
    background: {theme["page_bg"]};
    color: {theme["text"]};
}}
[data-testid="stAppViewContainer"],
[data-testid="stHeader"] {{
    background: {theme["page_bg"]};
}}
[data-testid="stExpander"] details {{
    background: {theme["surface_strong"]};
    border-color: {theme["border"]};
}}
[data-testid="stExpander"] summary {{
    color: {theme["text"]};
}}
[data-testid="stExpander"] details[open] summary {{
    background: {theme["surface_strong"]};
    border-bottom: 1px solid {theme["border"]};
}}
[data-testid="stSelectbox"] div[data-baseweb="select"] > div {{
    background: {theme["surface_strong"]};
    border-color: {theme["border"]};
    color: {theme["text"]};
}}
[data-testid="stSelectbox"] svg {{
    color: {theme["ok"]};
}}
[data-testid="stDownloadButton"] button,
[data-testid="stButton"] button {{
    background: {theme["surface_strong"]};
    border-color: {theme["border"]};
    color: {theme["text"]};
}}
[data-testid="stVegaLiteChart"] {{
    background: {theme["surface_strong"]};
    border: 1px solid {theme["border"]};
    border-radius: 0.35rem;
    padding: 0.25rem;
}}
[data-testid="stCodeBlock"] pre {{
    background: {theme["code_bg"]};
    border: 1px solid {theme["row_border"]};
    border-radius: 0.42rem;
    color: {theme["code_text"]};
}}
[data-testid="stCodeBlock"] code {{
    color: {theme["code_text"]};
}}
"""
    st.markdown(
        f"""
<style>
{light_page_override}
.litlaunch-meta-row {{
    align-items: center;
    display: flex;
    flex-wrap: wrap;
    gap: 0.55rem;
    margin: 0.35rem 0 0.2rem 0;
}}
.litlaunch-meta-label {{
    color: {theme["blue"]};
    font-size: 0.88rem;
    font-weight: 700;
}}
.litlaunch-slug {{
    background: {theme["surface"]};
    border: 1px solid rgba(62, 180, 137, 0.35);
    border-radius: 0.35rem;
    color: {theme["ok"]};
    display: inline-block;
    font-family: ui-monospace, SFMono-Regular, Consolas, "Liberation Mono", monospace;
    font-size: 0.84rem;
    font-weight: 700;
    line-height: 1.35;
    padding: 0.14rem 0.42rem;
}}
.litlaunch-muted {{
    color: {theme["muted"]};
    font-size: 0.9rem;
    line-height: 1.45;
}}
.litlaunch-section {{
    margin-top: 2.05rem;
}}
.litlaunch-section-compact {{
    margin-top: 1.35rem;
}}
.litlaunch-summary-value {{
    font-size: 2rem;
    font-weight: 700;
    line-height: 1.15;
    margin-top: 0.12rem;
}}
.litlaunch-summary-label {{
    color: {theme["text"]};
    font-size: 0.88rem;
    line-height: 1.35;
}}
.litlaunch-text-ok {{
    color: {theme["ok"]};
}}
.litlaunch-text-info {{
    color: {theme["warning"]};
}}
.litlaunch-text-warning {{
    color: {theme["warning"]};
}}
.litlaunch-text-error {{
    color: {theme["error"]};
}}
.litlaunch-notice {{
    border-left: 3px solid #1A73E8;
    border-radius: 0.42rem;
    margin: 0.45rem 0;
    padding: 0.55rem 0.75rem;
    color: {theme["text"]};
}}
.litlaunch-notice-info {{
    background: {theme["info_bg"]};
    border-left-color: {theme["blue"]};
}}
.litlaunch-notice-ok {{
    background: {theme["ok_bg"]};
    border-left-color: {theme["ok"]};
}}
.litlaunch-notice-warning {{
    background: {theme["warning_bg"]};
    border-left-color: {theme["warning"]};
}}
.litlaunch-notice-error {{
    background: {theme["error_bg"]};
    border-left-color: {theme["error"]};
}}
.litlaunch-posture-card {{
    background: {theme["surface"]};
    border: 1px solid {theme["border"]};
    border-left: 4px solid {theme["blue"]};
    border-radius: 0.48rem;
    min-height: 6rem;
    padding: 0.72rem 0.78rem;
}}
.litlaunch-posture-label {{
    color: {theme["blue"]};
    font-size: 0.82rem;
    font-weight: 800;
    margin-bottom: 0.35rem;
}}
.litlaunch-posture-value {{
    color: {theme["surface_text"]};
    font-size: 1.18rem;
    font-weight: 750;
    line-height: 1.25;
}}
.litlaunch-posture-status {{
    color: {theme["muted"]};
    font-size: 0.78rem;
    margin-top: 0.38rem;
}}
.litlaunch-status-ok {{
    border-left-color: {theme["ok"]};
}}
.litlaunch-status-info {{
    border-left-color: {theme["warning"]};
}}
.litlaunch-status-warning {{
    border-left-color: {theme["warning"]};
}}
.litlaunch-status-error {{
    border-left-color: {theme["error"]};
}}
.litlaunch-row {{
    background: {theme["surface_soft"]};
    border: 1px solid {theme["row_border"]};
    border-left: 3px solid {theme["blue"]};
    border-radius: 0.42rem;
    margin: 0.42rem 0;
    padding: 0.55rem 0.7rem;
}}
.litlaunch-row-title {{
    color: {theme["surface_text"]};
    font-weight: 750;
}}
.litlaunch-row-message {{
    color: {theme["message"]};
    margin-top: 0.12rem;
}}
.litlaunch-row-detail {{
    color: {theme["muted"]};
    font-size: 0.86rem;
    margin-top: 0.28rem;
}}
.litlaunch-pill {{
    border-radius: 999px;
    display: inline-block;
    font-size: 0.72rem;
    font-weight: 800;
    margin-right: 0.45rem;
    padding: 0.05rem 0.42rem;
    text-transform: uppercase;
}}
.litlaunch-pill-ok {{
    background: {theme["ok_pill_bg"]};
    color: {theme["ok"]};
}}
.litlaunch-pill-info {{
    background: {theme["warning_bg"]};
    color: {theme["warning"]};
}}
.litlaunch-pill-warning {{
    background: {theme["warning_bg"]};
    color: {theme["warning"]};
}}
.litlaunch-pill-error {{
    background: {theme["error_pill_bg"]};
    color: {theme["error"]};
}}
.litlaunch-session-card {{
    background: {theme["surface_soft"]};
    border: 1px solid {theme["row_border"]};
    border-left: 4px solid {theme["blue"]};
    border-radius: 0.48rem;
    margin: 0.52rem 0 0.72rem 0;
    padding: 0.75rem 0.85rem;
}}
.litlaunch-session-title {{
    color: {theme["surface_text"]};
    font-size: 1.08rem;
    font-weight: 800;
    line-height: 1.3;
}}
.litlaunch-session-subtitle {{
    color: {theme["message"]};
    font-size: 0.92rem;
    line-height: 1.45;
    margin-top: 0.18rem;
}}
.litlaunch-session-grid {{
    display: grid;
    gap: 0.45rem 0.85rem;
    grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr));
    margin-top: 0.68rem;
}}
.litlaunch-session-field-label {{
    color: {theme["muted"]};
    font-size: 0.76rem;
    font-weight: 750;
    text-transform: uppercase;
}}
.litlaunch-session-field-value {{
    color: {theme["surface_text"]};
    font-size: 0.92rem;
    font-weight: 650;
    margin-top: 0.08rem;
}}
.litlaunch-console {{
    background: {theme["code_bg"]};
    border: 1px solid {theme["row_border"]};
    border-radius: 0.48rem;
    color: {theme["code_text"]};
    font-family: ui-monospace, SFMono-Regular, Consolas, "Liberation Mono", monospace;
    font-size: 0.88rem;
    line-height: 1.55;
    margin-top: 0.7rem;
    overflow-x: auto;
    padding: 0.72rem 0.82rem;
    white-space: pre;
}}
.litlaunch-console-ok {{
    color: {theme["ok"]};
}}
.litlaunch-console-warn {{
    color: {theme["warning"]};
}}
.litlaunch-console-error {{
    color: {theme["error"]};
}}
.litlaunch-console-phase {{
    color: {theme["blue"]};
    font-weight: 800;
}}
.litlaunch-console-text {{
    color: {theme["code_text"]};
}}
</style>
        """,
        unsafe_allow_html=True,
    )


def _theme_tokens() -> dict[str, str]:
    if THEME == "dark":
        return _THEME_DARK
    if THEME == "light":
        return _THEME_LIGHT
    return _THEME_AUTO


def _chart_theme_tokens() -> dict[str, str]:
    if THEME == "light":
        return _THEME_LIGHT
    return _THEME_DARK


def _chart_config(theme: dict[str, str]) -> dict[str, Any]:
    return {
        "background": theme["chart_bg"],
        "axis": {
            "domainColor": theme["chart_grid"],
            "gridColor": theme["chart_grid"],
            "labelColor": theme["chart_text"],
            "titleColor": theme["chart_text"],
        },
        "legend": {
            "labelColor": theme["chart_text"],
            "titleColor": theme["chart_text"],
        },
        "view": {"stroke": "transparent"},
    }


def _chart_axis_config(theme: dict[str, str], *, title: str) -> dict[str, str]:
    return {
        "domainColor": theme["chart_grid"],
        "gridColor": theme["chart_grid"],
        "labelColor": theme["chart_text"],
        "title": title,
        "titleColor": theme["chart_text"],
    }


def _render_page_intro(st: Any) -> None:
    st.caption(
        "A Streamlit-native support surface generated by LitLaunch and owned by "
        "this application."
    )
    if APP_NAME or PROFILE_NAME:
        parts: list[str] = []
        if APP_NAME:
            parts.append(_meta_pair("App", APP_NAME))
        if PROFILE_NAME:
            parts.append(_meta_pair("LitLaunch profile", PROFILE_NAME))
        st.markdown(
            f"<div class='litlaunch-meta-row'>{''.join(parts)}</div>",
            unsafe_allow_html=True,
        )


def _render_collection_error(st: Any, message: str | None, detail: str | None) -> None:
    st.error("Could not collect LitLaunch diagnostics.")
    if message:
        st.caption(message)
    if detail:
        with st.expander("Technical details"):
            st.code(detail)


def _render_summary(st: Any, data: dict[str, Any]) -> None:
    _render_section_spacer(st)
    st.subheader("Runtime Summary")
    columns = st.columns(4)
    errors = int(data.get("errors", 0) or 0)
    warnings = int(data.get("warnings", 0) or 0)
    diagnostics_status = "OK" if data.get("ok") else "Needs attention"
    diagnostics_level = "ok" if data.get("ok") else ("error" if errors else "warning")
    with columns[0]:
        _render_summary_value(st, "Diagnostics", diagnostics_status, diagnostics_level)
    with columns[1]:
        _render_summary_value(st, "Errors", str(errors), "error" if errors else "ok")
    with columns[2]:
        _render_summary_value(
            st,
            "Warnings",
            str(warnings),
            "warning" if warnings else "ok",
        )
    with columns[3]:
        _render_summary_value(
            st,
            "LitLaunch",
            str(data.get("litlaunch_version", "unknown")),
            "ok",
        )

    metadata = {
        "App": APP_NAME or "not configured",
        "Profile": PROFILE_NAME or "not configured",
        "Project root": str(_project_root()),
        "Generated": str(data.get("generated_at_utc", "unknown")),
    }
    _render_section_spacer(st, compact=True)
    with st.expander("Runtime metadata", expanded=False):
        _render_key_value_rows(st, metadata)


def _render_posture_cards(st: Any, data: dict[str, Any]) -> None:
    _render_section_spacer(st)
    st.subheader("Posture")
    sections = _sections(data)
    cards = (
        (
            "Runtime Governance",
            _item_message(sections, "Runtime Governance", "Launch posture"),
            _item_status(sections, "Runtime Governance", "Launch posture"),
        ),
        (
            "Runtime Exposure",
            _item_message(sections, "Runtime Exposure", "Exposure scope"),
            _item_status(sections, "Runtime Exposure", "Exposure scope"),
        ),
        (
            "Transport Security",
            _item_message(sections, "Transport Security", "TLS configuration"),
            _item_status(sections, "Transport Security", "TLS configuration"),
        ),
        (
            "Browser/Platform",
            _item_message(sections, "Browsers", "Browser resolution"),
            _item_status(sections, "Browsers", "Browser resolution"),
        ),
    )
    columns = st.columns(len(cards))
    for column, (label, value, status) in zip(columns, cards):
        with column:
            _render_posture_card(st, label, _compact_metric_value(label, value), status)


def _render_operational_snapshot(st: Any, data: dict[str, Any]) -> None:
    _render_section_spacer(st)
    st.subheader("Operational Snapshot")
    status_column, activity_column = st.columns(2)
    with status_column:
        _render_status_mix_chart(st, data)
    with activity_column:
        event_counts = _event_category_counts()
        if event_counts:
            _render_event_mix_chart(st, event_counts)
        else:
            _render_section_attention_chart(st, data)


def _render_status_mix_chart(st: Any, data: dict[str, Any]) -> None:
    st.markdown("**Diagnostics Status Mix**")
    rows = _status_mix_rows(data)
    theme = _chart_theme_tokens()
    spec = {
        "background": theme["chart_bg"],
        "height": 220,
        "mark": {"type": "bar", "cornerRadiusEnd": 3},
        "encoding": {
            "y": {
                "field": "status",
                "type": "nominal",
                "sort": None,
                "axis": _chart_axis_config(theme, title="status"),
            },
            "x": {
                "field": "count",
                "type": "quantitative",
                "axis": _chart_axis_config(theme, title="count"),
            },
            "color": {
                "field": "color",
                "type": "nominal",
                "scale": None,
                "legend": None,
            },
            "tooltip": [
                {"field": "status", "type": "nominal"},
                {"field": "count", "type": "quantitative"},
            ],
        },
        "config": _chart_config(theme),
    }
    st.vega_lite_chart(
        rows,
        spec,
        width="stretch",
    )


def _render_event_mix_chart(st: Any, counts: dict[str, int]) -> None:
    st.markdown("**Runtime Event Mix**")
    rows = [
        {"category": category, "count": count}
        for category, count in sorted(counts.items())
    ]
    theme = _chart_theme_tokens()
    spec = {
        "background": theme["chart_bg"],
        "height": 220,
        "mark": {"type": "bar", "cornerRadiusEnd": 3},
        "encoding": {
            "x": {
                "field": "category",
                "type": "nominal",
                "axis": _chart_axis_config(theme, title="category"),
            },
            "y": {
                "field": "count",
                "type": "quantitative",
                "axis": _chart_axis_config(theme, title="count"),
            },
            "color": {"value": theme["ok"]},
            "tooltip": [
                {"field": "category", "type": "nominal"},
                {"field": "count", "type": "quantitative"},
            ],
        },
        "config": _chart_config(theme),
    }
    st.vega_lite_chart(
        rows,
        spec,
        width="stretch",
    )


def _render_section_attention_chart(st: Any, data: dict[str, Any]) -> None:
    st.markdown("**Section Attention Map**")
    rows = _section_attention_rows(data)
    if not rows:
        _render_notice(st, "info", "No section attention data is available.")
        return
    theme = _chart_theme_tokens()
    spec = {
        "background": theme["chart_bg"],
        "height": 220,
        "mark": {"type": "bar", "cornerRadiusEnd": 3},
        "transform": [{"fold": ["errors", "warnings"], "as": ["severity", "count"]}],
        "encoding": {
            "x": {
                "field": "section",
                "type": "nominal",
                "axis": _chart_axis_config(theme, title="section"),
            },
            "y": {
                "field": "count",
                "type": "quantitative",
                "axis": _chart_axis_config(theme, title="count"),
            },
            "color": {
                "field": "severity",
                "type": "nominal",
                "scale": {
                    "domain": ["errors", "warnings"],
                    "range": [theme["error"], theme["warning"]],
                },
            },
            "tooltip": [
                {"field": "section", "type": "nominal"},
                {"field": "severity", "type": "nominal"},
                {"field": "count", "type": "quantitative"},
            ],
        },
        "config": _chart_config(theme),
    }
    st.vega_lite_chart(
        rows,
        spec,
        width="stretch",
    )


def _render_artifact_actions(st: Any, report: Any) -> None:
    from litlaunch import (
        HTMLDiagnosticsRenderer,
        JSONDiagnosticsRenderer,
        SanitizedBundleRenderer,
    )

    html_report = HTMLDiagnosticsRenderer(include_details=True).render(report)
    json_report = JSONDiagnosticsRenderer().render(report)
    support_bundle = SanitizedBundleRenderer(include_details=True).render(report)
    artifacts = {
        "HTML report": {
            "file_name": "litlaunch-report.html",
            "content": html_report,
            "mime": "text/html",
        },
        "JSON diagnostics": {
            "file_name": "litlaunch-report.json",
            "content": json_report,
            "mime": "application/json",
        },
        "Support bundle": {
            "file_name": "litlaunch-support-bundle.txt",
            "content": support_bundle,
            "mime": "text/plain",
        },
    }

    _render_section_spacer(st)
    st.subheader("Support Artifacts")
    _render_muted(
        st,
        "Downloads are generated in memory. Writes create persistent artifacts "
        "under .litlaunch/reports/.",
    )
    download_column, write_column = st.columns(2)
    _render_download_artifact_group(st, download_column, artifacts)
    _render_write_artifact_group(st, write_column, artifacts)


def _render_download_artifact_group(
    st: Any,
    column: Any,
    artifacts: dict[str, dict[str, str]],
) -> None:
    with column:
        label = st.selectbox(
            "Download Artifact",
            options=list(artifacts),
            key="litlaunch_download_artifact_select",
        )
        artifact = artifacts[label]
        st.download_button(
            "Download",
            data=artifact["content"].encode("utf-8"),
            file_name=artifact["file_name"],
            mime=artifact["mime"],
            key="litlaunch_download_artifact_button",
        )


def _render_write_artifact_group(
    st: Any,
    column: Any,
    artifacts: dict[str, dict[str, str]],
) -> None:
    with column:
        label = st.selectbox(
            "Write Artifact",
            options=list(artifacts),
            key="litlaunch_write_artifact_select",
        )
        artifact = artifacts[label]
        if st.button("Write", key="litlaunch_write_artifact_button"):
            path = _write_report_artifact(artifact["file_name"], artifact["content"])
            _render_notice(st, "ok", f"Wrote {label}.")
            st.code(str(path))


def _write_report_artifact(file_name: str, content: str) -> Path:
    from litlaunch.artifacts import reports_dir

    report_dir = reports_dir(_project_root(), create=True)
    output_path = report_dir / file_name
    output_path.write_text(content, encoding="utf-8")
    return output_path


def _render_sections(st: Any, data: dict[str, Any]) -> None:
    _render_section_spacer(st)
    st.subheader("Diagnostics Details")
    sections = _sections(data)
    for section in data.get("sections", []):
        title = str(section.get("title", "Untitled section"))
        status = _section_status(sections, title)
        expanded = title in {
            "Runtime Governance",
            "Runtime Exposure",
            "Transport Security",
        }
        with st.expander(f"{title} - {status}", expanded=expanded):
            for item in section.get("items", []):
                _render_item(st, item)


def _render_item(st: Any, item: dict[str, Any]) -> None:
    status = str(item.get("status", "info")).lower()
    name = str(item.get("name", "Item"))
    message = str(item.get("message", ""))
    detail = item.get("detail")
    _render_diagnostic_row(st, status, name, message, str(detail) if detail else None)


def _render_event_trail(st: Any) -> None:
    if not INCLUDE_EVENTS:
        return

    _render_runtime_sessions(st)


def _render_runtime_sessions(st: Any) -> None:
    if not INCLUDE_EVENTS:
        return

    _render_section_spacer(st)
    st.subheader("Runtime Event Trail")
    event_path = _runtime_event_log_path()
    if event_path is None:
        _render_notice(
            st,
            "info",
            "No runtime event log path is configured for this generated page.",
        )
        return

    if not event_path.is_file():
        _render_notice(st, "info", "No runtime event log found.")
        st.code(str(event_path))
        return

    lines = event_path.read_text(encoding="utf-8", errors="replace").splitlines()
    records = _runtime_event_records_from_lines(lines)
    sessions = _group_runtime_sessions(records)
    if not sessions:
        _render_notice(
            st,
            "info",
            "No structured runtime sessions were found in the event log.",
        )
    else:
        _render_muted(
            st,
            f"Showing {min(len(sessions), 5)} of {len(sessions)} runtime sessions "
            "from newest to oldest.",
        )
        for index, session in enumerate(sessions[:5]):
            summary = _summarize_runtime_session(session)
            label = "Latest Session" if index == 0 else f"Previous Session {index}"
            with st.expander(
                f"{label} - {summary['status']}",
                expanded=index == 0,
            ):
                _render_runtime_session_summary(st, summary)
                _render_runtime_session_console(st, session)
    _render_raw_event_trail(st, event_path, lines)


def _render_raw_event_trail(st: Any, event_path: Path, lines: list[str]) -> None:
    recent_lines = lines[-80:]
    with st.expander("Raw Runtime Event Trail", expanded=False):
        _render_muted(st, f"Showing {len(recent_lines)} recent lines from:")
        st.code(str(event_path))
        st.code("\n".join(recent_lines) or "No events recorded yet.")


def _runtime_event_records_from_lines(lines: list[str]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for line in lines:
        record = _parse_runtime_event_record(line)
        if record is not None:
            records.append(record)
    return records


def _parse_runtime_event_record(line: str) -> dict[str, Any] | None:
    text = line.strip()
    if not text.startswith("{"):
        return None
    try:
        record = json.loads(text)
    except Exception:
        return None
    if not isinstance(record, dict):
        return None

    name = record.get("name")
    category = record.get("category")
    level = record.get("level", "info")
    timestamp = record.get("timestamp")
    message = record.get("message", "")
    details = record.get("details", {})
    if not isinstance(name, str) or not name.strip():
        return None
    if not isinstance(category, str) or not category.strip():
        return None
    if not isinstance(level, str):
        level = "info"
    if not isinstance(timestamp, str):
        timestamp = ""
    if not isinstance(message, str):
        message = ""
    if not isinstance(details, dict):
        details = {}

    return {
        "name": name.strip(),
        "category": category.strip(),
        "level": _normalize_event_level(level),
        "timestamp": timestamp.strip(),
        "message": message.strip(),
        "details": details,
    }


def _group_runtime_sessions(
    records: list[dict[str, Any]],
) -> list[list[dict[str, Any]]]:
    sessions: list[list[dict[str, Any]]] = []
    current: list[dict[str, Any]] = []
    for record in records:
        if record.get("name") == "launch_planned":
            if current:
                sessions.append(current)
            current = [record]
        elif current:
            current.append(record)
        else:
            current = [record]
    if current:
        sessions.append(current)
    return list(reversed(sessions))


def _summarize_runtime_session(session: list[dict[str, Any]]) -> dict[str, Any]:
    names = {str(record.get("name", "")) for record in session}
    levels = {
        _normalize_event_level(str(record.get("level", "info")))
        for record in session
    }
    start_time = _event_timestamp(session[0]) if session else None
    end_time = _session_end_time(session)

    status = "Running"
    status_level = "ok"
    if "error" in levels or "hook_failed" in names:
        status = "Error"
        status_level = "error"
    elif "warning" in levels:
        status = "Warning"
        status_level = "warning"
    elif "backend_stopped" in names or "port_released" in names:
        status = "Clean shutdown"
        status_level = "ok"
    elif "shutdown_requested" in names:
        status = "Shutdown requested"
        status_level = "info"

    mode = _first_event_detail(session, "mode") or "unknown"
    browser = _first_event_detail(session, "browser")
    host = _first_event_detail(session, "host")
    port = _first_event_detail(session, "port")
    pid = _first_event_detail(session, "pid")
    monitor_target = _first_event_detail(session, "target")
    hook_successes = sum(
        1 for record in session if record.get("name") == "hook_succeeded"
    )
    hook_failures = sum(1 for record in session if record.get("name") == "hook_failed")

    title = f"{_display_mode(mode)} launch session"
    if browser:
        title = f"{_display_mode(mode)} launched in {browser}"

    subtitle_parts: list[str] = []
    if host and port:
        subtitle_parts.append(f"Backend healthy on {host}:{port}")
    elif port:
        subtitle_parts.append(f"Backend healthy on port {port}")
    if monitor_target:
        subtitle_parts.append(f"Monitoring window: {monitor_target}")
    elif "monitor_started" in names:
        subtitle_parts.append("Window monitoring started")

    fields = {
        "Started": _format_timestamp(start_time) if start_time else "unknown",
        "Duration": _format_duration(start_time, end_time) if end_time else "running",
        "Status": status,
        "Mode": _display_mode(mode),
    }
    if browser:
        fields["Browser"] = browser
    if host:
        fields["Host"] = host
    if port:
        fields["Port"] = port
    if pid:
        fields["Backend PID"] = pid
    if hook_successes or hook_failures:
        fields["Hooks"] = f"{hook_successes} completed, {hook_failures} failed"

    return {
        "title": title,
        "subtitle": " - ".join(subtitle_parts) or "Runtime lifecycle events recorded.",
        "status": status,
        "status_level": status_level,
        "fields": fields,
    }


def _render_runtime_session_summary(st: Any, summary: dict[str, Any]) -> None:
    fields = summary.get("fields", {})
    field_html = ""
    if isinstance(fields, dict):
        for label, value in fields.items():
            field_html += (
                "<div>"
                f"<div class='litlaunch-session-field-label'>{_html(label)}</div>"
                f"<div class='litlaunch-session-field-value'>{_html(value)}</div>"
                "</div>"
            )
    st.markdown(
        (
            f"<div class='litlaunch-session-card "
            f"{_status_class(str(summary.get('status_level', 'info')))}'>"
            "<div class='litlaunch-session-title'>"
            f"{_html(summary.get('title', 'Runtime session'))}</div>"
            "<div class='litlaunch-session-subtitle'>"
            f"{_html(summary.get('subtitle', ''))}</div>"
            f"<div class='litlaunch-session-grid'>{field_html}</div>"
            "</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_runtime_session_timeline(
    st: Any,
    session: list[dict[str, Any]],
) -> None:
    _render_runtime_session_console(st, session)


def _render_runtime_session_console(
    st: Any,
    session: list[dict[str, Any]],
) -> None:
    lines = [_console_event_line(record) for record in session[-32:]]
    if not lines:
        lines = ["<span class='litlaunch-console-text'>No events recorded.</span>"]
    st.markdown(
        f"<div class='litlaunch-console'>{''.join(lines)}</div>",
        unsafe_allow_html=True,
    )


def _console_event_line(record: dict[str, Any]) -> str:
    level = _normalize_event_level(str(record.get("level", "info")))
    category = str(record.get("category", "runtime"))
    phase = _console_phase_label(category)
    message = _console_event_message(record)
    status = _console_status_label(level)
    status_class = "litlaunch-console-warn" if level == "warning" else (
        "litlaunch-console-error" if level == "error" else "litlaunch-console-ok"
    )
    return (
        f"<span class='{status_class}'>{_html(status)}</span> "
        f"<span class='litlaunch-console-phase'>{_html(phase)}:</span> "
        f"<span class='litlaunch-console-text'>{_html(message)}</span>\n"
    )


def _console_status_label(level: str) -> str:
    normalized = _normalize_event_level(level)
    if normalized == "error":
        return "[ error  ]"
    if normalized == "warning":
        return "[  warn  ]"
    return "[   ok   ]"


def _console_phase_label(category: str) -> str:
    labels = {
        "launch": "Launch",
        "backend": "Backend",
        "health": "Health",
        "browser": "Browser",
        "monitor": "Monitor",
        "hook": "Hook",
        "shutdown": "Shutdown",
        "port": "Port",
    }
    normalized = str(category or "runtime").strip().lower()
    return labels.get(normalized, "Runtime")


def _console_event_message(record: dict[str, Any]) -> str:
    name = str(record.get("name", ""))
    details = record.get("details")
    if not isinstance(details, dict):
        details = {}
    if name == "launch_planned":
        mode = _safe_detail(details, "mode")
        browser = _safe_detail(details, "browser")
        target = f" in {browser}" if browser else ""
        return f"Planned {mode or 'runtime'} launch{target}."
    if name == "backend_starting":
        return _with_host_port("Starting Streamlit", details) + "."
    if name == "backend_started":
        pid = _safe_detail(details, "pid")
        suffix = f" with PID {pid}" if pid else ""
        return _with_host_port(f"Started Streamlit{suffix}", details) + "."
    if name == "backend_start_failed":
        return "Streamlit backend failed before becoming healthy."
    if name == "health_ready":
        return _with_host_port("Ready", details) + "."
    if name == "browser_launched":
        browser = _safe_detail(details, "browser")
        mode = _safe_detail(details, "mode")
        if browser and mode:
            return f"Launched {browser} for {mode} mode."
        if browser:
            return f"Launched {browser}."
        return "Browser launched."
    if name == "monitor_started":
        mode = _safe_detail(details, "mode")
        target = _safe_detail(details, "target")
        if target:
            return f"Monitoring {target}."
        return f"Monitoring {mode or 'runtime'} window."
    if name == "shutdown_requested":
        return "Shutdown requested."
    if name == "hook_succeeded":
        label = _safe_detail(details, "label")
        return f"{label or 'Shutdown hook'} completed."
    if name == "hook_failed":
        label = _safe_detail(details, "label")
        return f"{label or 'Shutdown hook'} failed."
    if name == "backend_stopped":
        returncode = _safe_detail(details, "returncode")
        if returncode is not None:
            return f"Backend stopped with return code {returncode}."
        return "Backend stopped."
    if name == "port_released":
        port = _safe_detail(details, "port")
        return f"Port {port} released." if port else "Backend port released."
    message = str(record.get("message", "")).strip()
    return message or _friendly_event_name(name)


def _with_host_port(message: str, details: dict[str, Any]) -> str:
    host = _safe_detail(details, "host")
    port = _safe_detail(details, "port")
    if host and port:
        return f"{message} on {host}:{port}"
    if port:
        return f"{message} on port {port}"
    return message


def _safe_detail(details: dict[str, Any], key: str) -> str | None:
    value = details.get(key)
    if isinstance(value, str):
        value = value.strip()
        return value or None
    if isinstance(value, int | float | bool):
        return str(value)
    return None


def _friendly_event_name(name: str) -> str:
    labels = {
        "launch_planned": "Launch planned",
        "backend_starting": "Backend startup requested",
        "backend_started": "Backend process started",
        "backend_start_failed": "Backend startup failed",
        "health_ready": "Health check passed",
        "browser_launched": "Browser launched",
        "monitor_started": "Window monitoring started",
        "shutdown_requested": "Shutdown requested",
        "hook_succeeded": "Shutdown hook completed",
        "hook_failed": "Shutdown hook failed",
        "backend_stopped": "Backend stopped",
        "port_released": "Port released",
    }
    return labels.get(name, name.replace("_", " ").strip().title() or "Runtime event")


def _session_end_time(session: list[dict[str, Any]]) -> datetime | None:
    terminal_names = {
        "port_released",
        "backend_stopped",
        "backend_start_failed",
        "hook_failed",
    }
    for record in reversed(session):
        if record.get("name") in terminal_names:
            return _event_timestamp(record)
    return None


def _event_timestamp(record: dict[str, Any]) -> datetime | None:
    timestamp = record.get("timestamp")
    if not isinstance(timestamp, str) or not timestamp.strip():
        return None
    text = timestamp.strip().replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(text)
    except ValueError:
        return None


def _format_timestamp(value: datetime | None) -> str:
    if value is None:
        return "unknown"
    return value.strftime("%Y-%m-%d %H:%M:%S")


def _format_duration(start: datetime | None, end: datetime | None) -> str:
    if start is None or end is None:
        return "unknown"
    seconds = max(0.0, (end - start).total_seconds())
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes, remainder = divmod(seconds, 60)
    if minutes < 60:
        return f"{int(minutes)}m {int(remainder)}s"
    hours, minutes = divmod(minutes, 60)
    return f"{int(hours)}h {int(minutes)}m"


def _first_event_detail(session: list[dict[str, Any]], key: str) -> str | None:
    for record in session:
        details = record.get("details")
        if not isinstance(details, dict) or key not in details:
            continue
        value = details.get(key)
        if isinstance(value, str):
            value = value.strip()
            return value or None
        if isinstance(value, int | float | bool):
            return str(value)
    return None


def _display_mode(mode: str | None) -> str:
    if not mode:
        return "Runtime"
    normalized = str(mode).strip().lower()
    if normalized == "webapp":
        return "Webapp"
    if normalized == "browser":
        return "Browser"
    return normalized.replace("_", " ").title()


def _normalize_event_level(level: str) -> str:
    normalized = str(level or "info").strip().lower()
    if normalized == "warning":
        return "warning"
    if normalized == "error":
        return "error"
    return "info"


def _status_mix_rows(data: dict[str, Any]) -> list[dict[str, Any]]:
    theme = _chart_theme_tokens()
    counts = {"ok": 0, "info": 0, "warning": 0, "error": 0}
    for section in data.get("sections", []):
        for item in section.get("items", []):
            status = _normalize_status(str(item.get("status", "info")))
            counts[status] += 1
    return [
        {"status": "OK", "count": counts["ok"], "color": theme["ok"]},
        {"status": "Info", "count": counts["info"], "color": theme["blue"]},
        {"status": "Warning", "count": counts["warning"], "color": theme["warning"]},
        {"status": "Error", "count": counts["error"], "color": theme["error"]},
    ]


def _section_attention_rows(data: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for section in data.get("sections", []):
        title = str(section.get("title", "Untitled"))
        warning_count = 0
        error_count = 0
        for item in section.get("items", []):
            status = _normalize_status(str(item.get("status", "info")))
            if status == "warning":
                warning_count += 1
            elif status == "error":
                error_count += 1
        if warning_count or error_count:
            rows.append(
                {
                    "section": title,
                    "warnings": warning_count,
                    "errors": error_count,
                }
            )
    return rows


def _event_category_counts() -> dict[str, int]:
    if not INCLUDE_EVENTS:
        return {}
    event_path = _runtime_event_log_path()
    if event_path is None:
        return {}
    if not event_path.is_file():
        return {}
    counts: dict[str, int] = {}
    for line in event_path.read_text(encoding="utf-8", errors="replace").splitlines():
        category = _extract_event_category(line)
        if category:
            counts[category] = counts.get(category, 0) + 1
    return counts


def _extract_event_category(line: str) -> str | None:
    json_category = _extract_json_event_category(line)
    if json_category:
        return json_category

    marker = "category="
    if marker in line:
        category = line.split(marker, 1)[1].split()[0].strip(" ,;")
        return category or None
    if "litlaunch_event" in line:
        parts = line.split()
        if len(parts) >= 4:
            value = parts[3].strip("[]")
            return value or None
    return None


def _extract_json_event_category(line: str) -> str | None:
    text = line.strip()
    if not text.startswith("{"):
        return None
    try:
        record = json.loads(text)
    except Exception:
        return None
    if not isinstance(record, dict):
        return None
    category = record.get("category")
    if not isinstance(category, str):
        return None
    category = category.strip()
    return category or None


def _render_posture_card(st: Any, label: str, value: str, status: str) -> None:
    status_class = _status_class(status)
    status_label = _status_label(status)
    st.markdown(
        (
            f"<div class='litlaunch-posture-card {status_class}'>"
            f"<div class='litlaunch-posture-label'>{_html(label)}</div>"
            f"<div class='litlaunch-posture-value'>{_html(value)}</div>"
            f"<div class='litlaunch-posture-status'>{_html(status_label)}</div>"
            "</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_summary_value(st: Any, label: str, value: str, status: str) -> None:
    status_class = f"litlaunch-text-{_normalize_status(status)}"
    st.markdown(
        (
            "<div>"
            f"<div class='litlaunch-summary-label'>{_html(label)}</div>"
            f"<div class='litlaunch-summary-value {status_class}'>{_html(value)}</div>"
            "</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_diagnostic_row(
    st: Any,
    status: str,
    name: str,
    message: str,
    detail: str | None,
) -> None:
    normalized = _normalize_status(status)
    detail_html = (
        f"<div class='litlaunch-row-detail'>{_html(detail)}</div>" if detail else ""
    )
    st.markdown(
        (
            f"<div class='litlaunch-row {_status_class(normalized)}'>"
            f"<span class='litlaunch-pill litlaunch-pill-{normalized}'>"
            f"{_html(_status_label(normalized))}</span>"
            f"<span class='litlaunch-row-title'>{_html(name)}</span>"
            f"<div class='litlaunch-row-message'>{_html(message)}</div>"
            f"{detail_html}</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_key_value_rows(st: Any, rows: dict[str, Any]) -> None:
    for label, value in rows.items():
        st.markdown(
            (
                "<div class='litlaunch-meta-row'>"
                f"<span class='litlaunch-meta-label'>{_html(str(label))}</span>"
                f"<span class='litlaunch-slug'>{_html(str(value))}</span>"
                "</div>"
            ),
            unsafe_allow_html=True,
        )


def _render_notice(st: Any, status: str, message: str) -> None:
    normalized = _normalize_status(status)
    st.markdown(
        (
            f"<div class='litlaunch-notice litlaunch-notice-{normalized}'>"
            f"{_html(message)}</div>"
        ),
        unsafe_allow_html=True,
    )


def _render_muted(st: Any, message: str) -> None:
    st.markdown(
        f"<div class='litlaunch-muted'>{_html(message)}</div>",
        unsafe_allow_html=True,
    )


def _render_section_spacer(st: Any, *, compact: bool = False) -> None:
    class_name = "litlaunch-section-compact" if compact else "litlaunch-section"
    st.markdown(f"<div class='{class_name}'></div>", unsafe_allow_html=True)


def _meta_pair(label: str, value: str) -> str:
    return (
        f"<span class='litlaunch-meta-label'>{_html(label)}</span>"
        f"<span class='litlaunch-slug'>{_html(value)}</span>"
    )


def _html(value: Any) -> str:
    return escape(str(value), quote=True)


def _normalize_status(status: str) -> str:
    normalized = str(status or "info").lower()
    if normalized in {"ok", "info", "warning", "error"}:
        return normalized
    return "info"


def _status_class(status: str) -> str:
    return f"litlaunch-status-{_normalize_status(status)}"


def _status_label(status: str) -> str:
    normalized = _normalize_status(status)
    if normalized == "ok":
        return "OK"
    if normalized == "warning":
        return "Warning"
    if normalized == "error":
        return "Error"
    return "Info"


def _sections(data: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    return {
        str(section.get("title", "")): list(section.get("items", []))
        for section in data.get("sections", [])
    }


def _section_status(sections: dict[str, list[dict[str, Any]]], title: str) -> str:
    items = sections.get(title, [])
    statuses = {str(item.get("status", "info")).lower() for item in items}
    if "error" in statuses:
        return "error"
    if "warning" in statuses:
        return "warning"
    if "ok" in statuses:
        return "ok"
    return "info"


def _item_message(
    sections: dict[str, list[dict[str, Any]]],
    title: str,
    item_name: str,
) -> str | None:
    for item in sections.get(title, []):
        if item.get("name") == item_name:
            return str(item.get("message", ""))
    return None


def _item_status(
    sections: dict[str, list[dict[str, Any]]],
    title: str,
    item_name: str,
) -> str:
    for item in sections.get(title, []):
        if item.get("name") == item_name:
            return str(item.get("status", "info")).lower()
    return _section_status(sections, title)


def _compact_metric_value(label: str, value: str | None) -> str:
    if not value:
        return "not reported"
    normalized = value.strip()
    if label == "Transport Security":
        if normalized == "not_configured":
            return "No TLS"
        if normalized == "configured":
            return "TLS"
        if normalized == "incomplete":
            return "Incomplete"
    if label == "Browser/Platform":
        if "Microsoft Edge" in normalized:
            return "Edge"
        if "Chrome" in normalized or "Chromium" in normalized:
            return "Chrome"
        if "Default browser" in normalized:
            return "Default"
    if normalized == "wildcard_bind":
        return "wildcard"
    return normalized.replace("_", " ")


def _project_root() -> Path:
    if PROJECT_ROOT:
        return Path(PROJECT_ROOT).expanduser().resolve()
    return Path.cwd()


def _resolve_project_path(value: str) -> Path:
    path = Path(value).expanduser()
    if path.is_absolute():
        return path
    return _project_root() / path


def _runtime_event_log_path() -> Path | None:
    if EVENT_LOG_ENV_VAR:
        env_value = os.environ.get(EVENT_LOG_ENV_VAR)
        if env_value:
            return _resolve_project_path(env_value)
    if EVENT_LOG_PATH:
        return _resolve_project_path(EVENT_LOG_PATH)
    return None
